import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['es', 'ca', 'en', 'zh_Hans', 'fr', 'de', 'ja', 'it', 'pt', 'ar'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? esText = '',
    String? caText = '',
    String? enText = '',
    String? zh_HansText = '',
    String? frText = '',
    String? deText = '',
    String? jaText = '',
    String? itText = '',
    String? ptText = '',
    String? arText = '',
  }) =>
      [
        esText,
        caText,
        enText,
        zh_HansText,
        frText,
        deText,
        jaText,
        itText,
        ptText,
        arText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // HomePage
  {
    '5p59bb07': {
      'es': 'Alojamiento',
      'ar': 'إقامة',
      'ca': 'Allotjament',
      'de': 'Unterkunft',
      'en': 'Accommodation',
      'fr': 'Hébergement',
      'it': 'Alloggio',
      'ja': '宿泊施設',
      'pt': 'Alojamento',
      'zh_Hans': '住宿',
    },
    'zm2qhvab': {
      'es': 'Rutas',
      'ar': 'الطرق',
      'ca': 'Rutes',
      'de': 'Routen',
      'en': 'Routes',
      'fr': 'Itinéraires',
      'it': 'Itinerari',
      'ja': 'ルート',
      'pt': 'Rotas',
      'zh_Hans': '路线',
    },
    'lqmg3r2v': {
      'es': 'Cultura',
      'ar': 'ثقافة',
      'ca': 'Cultura',
      'de': 'Kultur',
      'en': 'Culture',
      'fr': 'Culture',
      'it': 'Cultura',
      'ja': '文化',
      'pt': 'Cultura',
      'zh_Hans': '文化',
    },
    'z0wzt9ic': {
      'es': 'Entretenimiento',
      'ar': 'ترفيه',
      'ca': 'Entreteniment',
      'de': 'Unterhaltung',
      'en': 'Entertainment',
      'fr': 'Divertissement',
      'it': 'Divertimento',
      'ja': 'エンターテインメント',
      'pt': 'Entretenimento',
      'zh_Hans': '娱乐',
    },
    '4yiceu0u': {
      'es': 'Gastronomía',
      'ar': 'فن الطهو',
      'ca': 'Gastronomia',
      'de': 'Gastronomie',
      'en': 'Gastronomy',
      'fr': 'Gastronomie',
      'it': 'Gastronomia',
      'ja': '美食',
      'pt': 'Gastronomia',
      'zh_Hans': '美食',
    },
    '4ydsixl4': {
      'es': 'Transporte',
      'ar': 'ينقل',
      'ca': 'Transport',
      'de': 'Transport',
      'en': 'Transport',
      'fr': 'Transport',
      'it': 'Trasporto',
      'ja': '輸送',
      'pt': 'Transporte',
      'zh_Hans': '运输',
    },
    'l09hiqy3': {
      'es': 'Inicio',
      'ar': 'البدء',
      'ca': 'Inici',
      'de': 'Start',
      'en': 'Start',
      'fr': 'Début',
      'it': 'Inizio',
      'ja': '始める',
      'pt': 'Começar',
      'zh_Hans': '开始',
    },
  },
  // LoginScreen
  {
    '5gcik3v6': {
      'es': 'Correo electrónico',
      'ar': 'بريد إلكتروني',
      'ca': 'Email',
      'de': 'Email',
      'en': 'E-mail',
      'fr': 'E-mail',
      'it': 'E-mail',
      'ja': 'Eメール',
      'pt': 'E-mail',
      'zh_Hans': '电子邮件',
    },
    'o3n7jgl0': {
      'es': 'Contraseña',
      'ar': 'كلمة المرور',
      'ca': 'Password',
      'de': 'Passwort',
      'en': 'Password',
      'fr': 'Mot de passe',
      'it': 'Parola d\'ordine',
      'ja': 'パスワード',
      'pt': 'Senha',
      'zh_Hans': '密码',
    },
    'hizhv4wm': {
      'es': '¿Has olvidado la contraseña?',
      'ar': 'هل نسيت كلمة المرور؟',
      'ca': 'Heu oblidat la contrasenya?',
      'de': 'Haben Sie das Passwort vergessen?',
      'en': 'Have you forgotten the password?',
      'fr': 'Avez-vous oublié le mot de passe ?',
      'it': 'Hai dimenticato la password?',
      'ja': 'パスワードを忘れましたか?',
      'pt': 'Você esqueceu a senha?',
      'zh_Hans': '您忘记密码了吗？',
    },
    'azunv81k': {
      'es': 'Iniciar sesión',
      'ar': 'تسجيل الدخول',
      'ca': 'Iniciar sessió',
      'de': 'Anmeldung',
      'en': 'Log in',
      'fr': 'Commencer la session',
      'it': 'Login',
      'ja': 'ログイン',
      'pt': 'Iniciar sessão',
      'zh_Hans': '登录',
    },
    '6ukph6sq': {
      'es': '¿No tienes cuenta? ',
      'ar': 'لا يوجد لديك حساب؟',
      'ca': 'No tens compte?',
      'de': 'Sie haben noch kein Konto?',
      'en': 'You do not have an account?',
      'fr': 'Vous n\'avez pas de compte ?',
      'it': 'Non hai un account?',
      'ja': 'アカウントをお持ちではありませんか?',
      'pt': 'Você não tem uma conta?',
      'zh_Hans': '您还没有帐户？',
    },
    'wbaa3kht': {
      'es': 'Regístrate',
      'ar': 'اشتراك',
      'ca': 'Registra\'t',
      'de': 'Melden Sie sich an',
      'en': 'Sign up',
      'fr': 'S\'inscrire',
      'it': 'Iscrizione',
      'ja': 'サインアップ',
      'pt': 'cadastre-se',
      'zh_Hans': '报名',
    },
    'oz0dqpwj': {
      'es': 'Home',
      'ar': 'بيت',
      'ca': 'Home',
      'de': 'heim',
      'en': 'home',
      'fr': 'maison',
      'it': 'casa',
      'ja': '家',
      'pt': 'lar',
      'zh_Hans': '家',
    },
  },
  // RegisterScreen
  {
    'cgr5amfm': {
      'es': 'Crear cuenta',
      'ar': 'إنشاء حساب',
      'ca': 'Crear compte',
      'de': 'Benutzerkonto erstellen',
      'en': 'Create Account',
      'fr': 'Créer un compte',
      'it': 'Creare un account',
      'ja': 'アカウントを作成する',
      'pt': 'Criar uma conta',
      'zh_Hans': '创建账户',
    },
    'f1x0juen': {
      'es': 'Nombre',
      'ar': 'اسم',
      'ca': 'Nom',
      'de': 'Name',
      'en': 'Name',
      'fr': 'nom',
      'it': 'Nome',
      'ja': '名前',
      'pt': 'Nome',
      'zh_Hans': '姓名',
    },
    'l1lzw8ct': {
      'es': 'Apellido',
      'ar': 'اسم العائلة',
      'ca': 'Cognom',
      'de': 'Familienname, Nachname',
      'en': 'Last name',
      'fr': 'Le nom',
      'it': 'Cognome',
      'ja': '苗字',
      'pt': 'Sobrenome',
      'zh_Hans': '姓',
    },
    'vsta24il': {
      'es': 'Correo electrónico',
      'ar': 'بريد الكتروني',
      'ca': 'Correu electrònic',
      'de': 'Email',
      'en': 'Email',
      'fr': 'Courrier électronique',
      'it': 'E-mail',
      'ja': 'Eメール',
      'pt': 'Correio eletrônico',
      'zh_Hans': '电子邮件',
    },
    'o591izbt': {
      'es': 'Contraseña',
      'ar': 'كلمة المرور',
      'ca': 'Contrasenya',
      'de': 'Passwort',
      'en': 'Password',
      'fr': 'Mot de passe',
      'it': 'Parola d\'ordine',
      'ja': 'パスワード',
      'pt': 'Senha',
      'zh_Hans': '密码',
    },
    'zwsgyi9l': {
      'es': 'Confirmar contraseña',
      'ar': 'تأكيد كلمة المرور',
      'ca': 'Confirmar contrasenya',
      'de': 'Bestätige das Passwort',
      'en': 'Confirm Password',
      'fr': 'Confirmer mot de passe',
      'it': 'Conferma password',
      'ja': 'パスワードを認証する',
      'pt': 'confirmar senha',
      'zh_Hans': '确认密码',
    },
    'cjj2qci1': {
      'es': 'Regístrate',
      'ar': 'اشتراك',
      'ca': 'Registra\'t',
      'de': 'Melden Sie sich an',
      'en': 'Sign up',
      'fr': 'S\'inscrire',
      'it': 'Iscrizione',
      'ja': 'サインアップ',
      'pt': 'cadastre-se',
      'zh_Hans': '报名',
    },
    'xtxkqd32': {
      'es': 'Home',
      'ar': 'بيت',
      'ca': 'Home',
      'de': 'heim',
      'en': 'home',
      'fr': 'maison',
      'it': 'casa',
      'ja': '家',
      'pt': 'lar',
      'zh_Hans': '家',
    },
  },
  // SavedScreen
  {
    '53uhqzx3': {
      'es': 'Guardado',
      'ar': 'أنقذ',
      'ca': 'Desat',
      'de': 'Gerettet',
      'en': 'Saved',
      'fr': 'Enregistré',
      'it': 'Salvato',
      'ja': '保存されました',
      'pt': 'Salvou',
      'zh_Hans': '已保存',
    },
  },
  // SettingsPage
  {
    '7j0rx5df': {
      'es': 'Ajustes',
      'ar': 'إعدادات',
      'ca': 'Ajustaments',
      'de': 'Einstellungen',
      'en': 'Settings',
      'fr': 'Paramètres',
      'it': 'Impostazioni',
      'ja': '設定',
      'pt': 'Configurações',
      'zh_Hans': '设置',
    },
    '4bww7abw': {
      'es': 'CUENTA',
      'ar': 'حساب',
      'ca': 'COMPTE',
      'de': 'KONTO',
      'en': 'ACCOUNT',
      'fr': 'COMPTE',
      'it': 'ACCOUNT',
      'ja': 'アカウント',
      'pt': 'CONTA',
      'zh_Hans': '帐户',
    },
    'qu0zkjx4': {
      'es': 'Cuenta',
      'ar': 'حساب',
      'ca': 'Compte',
      'de': 'Konto',
      'en': 'Account',
      'fr': 'compte',
      'it': 'Account',
      'ja': 'アカウント',
      'pt': 'Conta',
      'zh_Hans': '帐户',
    },
    'bp1iejvo': {
      'es': 'GENERAL',
      'ar': 'عام',
      'ca': 'GENERAL',
      'de': 'ALLGEMEIN',
      'en': 'GENERAL',
      'fr': 'GÉNÉRAL',
      'it': 'GENERALE',
      'ja': '一般的な',
      'pt': 'EM GERAL',
      'zh_Hans': '一般的',
    },
    'bsf6pcnw': {
      'es': 'Idioma',
      'ar': 'لغة',
      'ca': 'Idioma',
      'de': 'Sprache',
      'en': 'Language',
      'fr': 'langage',
      'it': 'Lingua',
      'ja': '言語',
      'pt': 'Linguagem',
      'zh_Hans': '语言',
    },
    'beu2ltwe': {
      'es': 'Modo Oscuro',
      'ar': 'الوضع المظلم',
      'ca': 'Mode Fosc',
      'de': 'Dunkler Modus',
      'en': 'Dark Mode',
      'fr': 'Mode sombre',
      'it': 'Modalità scura',
      'ja': 'ダークモード',
      'pt': 'Modo escuro',
      'zh_Hans': '深色模式',
    },
    'qz3ksxa4': {
      'es': 'INFORMACIÓN',
      'ar': 'المساعدة والمعلومات',
      'ca': 'AJUDA I INFORMACIÓ',
      'de': 'HILFE UND INFORMATIONEN',
      'en': 'HELP AND INFORMATION',
      'fr': 'AIDE ET INFORMATIONS',
      'it': 'AIUTO E INFORMAZIONI',
      'ja': 'ヘルプと情報',
      'pt': 'AJUDA E INFORMAÇÃO',
      'zh_Hans': '帮助和信息',
    },
    'p7l0i191': {
      'es': 'Política de privacidad',
      'ar': 'سياسة الخصوصية',
      'ca': 'Política de privadesa',
      'de': 'Datenschutzrichtlinie',
      'en': 'Privacy Policy',
      'fr': 'Politique de confidentialité',
      'it': 'politica sulla riservatezza',
      'ja': 'プライバシーポリシー',
      'pt': 'Política de privacidade',
      'zh_Hans': '隐私政策',
    },
    'mwv9yuty': {
      'es': 'Términos y condiciones',
      'ar': 'الأحكام والشروط',
      'ca': 'Termes i condicions',
      'de': 'Geschäftsbedingungen',
      'en': 'Terms and Conditions',
      'fr': 'Termes et conditions',
      'it': 'Termini e Condizioni',
      'ja': '利用規約',
      'pt': 'Termos e Condições',
      'zh_Hans': '条款和条件',
    },
    'y1u943j4': {
      'es': 'Cerrar Sesión',
      'ar': 'تسجيل خروج',
      'ca': 'Tancar Sessió',
      'de': 'abmelden',
      'en': 'Sign off',
      'fr': 'Fermer la session',
      'it': 'cancella la sottoscrizione',
      'ja': 'サインオフ',
      'pt': 'Fechar Sessão',
      'zh_Hans': '搁笔',
    },
    'u8jprg6k': {
      'es': 'Ajustes',
      'ar': 'إعدادات',
      'ca': 'Ajustaments',
      'de': 'Einstellungen',
      'en': 'Settings',
      'fr': 'Paramètres',
      'it': 'Impostazioni',
      'ja': '設定',
      'pt': 'Configurações',
      'zh_Hans': '设置',
    },
  },
  // SearchScreen
  {
    'p6mcourm': {
      'es': 'Buscar...',
      'ar': 'بحث...',
      'ca': 'Buscar...',
      'de': 'Suche...',
      'en': 'Look for...',
      'fr': 'Chercher...',
      'it': 'Cercare...',
      'ja': '探す...',
      'pt': 'Procurar...',
      'zh_Hans': '寻找...',
    },
    '8shdbx1z': {
      'es': 'Buscar...',
      'ar': 'بحث...',
      'ca': 'Cerca...',
      'de': 'Suche...',
      'en': 'Search...',
      'fr': 'Chercher...',
      'it': 'Cercare...',
      'ja': '探す...',
      'pt': 'Procurar...',
      'zh_Hans': '寻找...',
    },
  },
  // MapsPage
  {
    'u03ovavx': {
      'es': 'Selecciona una localización',
      'ar': 'اختر موقعا',
      'ca': 'Selecciona una localització',
      'de': 'Wähle einen Ort',
      'en': 'Select a location',
      'fr': 'Sélectionnez un emplacement',
      'it': 'Seleziona una posizione',
      'ja': '場所を選択してください',
      'pt': 'Selecione um local',
      'zh_Hans': '选择地点',
    },
    '5v31jshv': {
      'es': 'Mapa',
      'ar': 'خريطة',
      'ca': 'Mapa',
      'de': 'Karte',
      'en': 'Map',
      'fr': 'Carte',
      'it': 'Carta geografica',
      'ja': '地図',
      'pt': 'Mapa',
      'zh_Hans': '地图',
    },
  },
  // ForgottenPassword1
  {
    '6hsske6j': {
      'es': 'Restablecer\ncontraseña',
      'ar': 'يعيد\nكلمة المرور',
      'ca': 'Restablir\ncontrasenya',
      'de': 'Wiederherstellen\nPasswort',
      'en': 'Restore\npassword',
      'fr': 'Restaurer\nmot de passe',
      'it': 'Ristabilire\nparola d\'ordine',
      'ja': '復元する\nパスワード',
      'pt': 'Restaurar\nsenha',
      'zh_Hans': '恢复\n密码',
    },
    'e7kcfbvq': {
      'es':
          'Te enviaremos un correo electrónico con un enlace para restablecer su contraseña, ingrese el correo electrónico asociado con su cuenta a continuación.',
      'ar':
          'سنرسل إليك بريدًا إلكترونيًا يحتوي على رابط لإعادة تعيين كلمة المرور الخاصة بك، أدخل البريد الإلكتروني المرتبط بحسابك أدناه.',
      'ca':
          'T\'enviarem un correu electrònic amb un enllaç per restablir la contrasenya, introduïu el correu electrònic associat amb el vostre compte a continuació.',
      'de':
          'Wir senden Ihnen eine E-Mail mit einem Link zum Zurücksetzen Ihres Passworts. Geben Sie unten die mit Ihrem Konto verknüpfte E-Mail-Adresse ein.',
      'en':
          'We will send you an email with a link to reset your password, enter the email associated with your account below.',
      'fr':
          'Nous vous enverrons un e-mail avec un lien pour réinitialiser votre mot de passe, entrez l\'e-mail associé à votre compte ci-dessous.',
      'it':
          'Ti invieremo un\'e-mail con un collegamento per reimpostare la password, inserisci di seguito l\'e-mail associata al tuo account.',
      'ja':
          'パスワードをリセットするためのリンクが記載された電子メールが送信されます。以下にアカウントに関連付けられた電子メールを入力してください。',
      'pt':
          'Enviaremos um e-mail com um link para redefinir sua senha, digite abaixo o e-mail associado à sua conta.',
      'zh_Hans': '我们将向您发送一封电子邮件，其中包含重置密码的链接，请在下面输入与您的帐户关联的电子邮件。',
    },
    '97hxw0ox': {
      'es': 'Correo electrónico',
      'ar': 'بريد الكتروني',
      'ca': 'Correu electrònic',
      'de': 'Email',
      'en': 'Email',
      'fr': 'Courrier électronique',
      'it': 'E-mail',
      'ja': 'Eメール',
      'pt': 'Correio eletrônico',
      'zh_Hans': '电子邮件',
    },
    'pj9l0n0s': {
      'es': 'Enviar email',
      'ar': 'ارسل بريد الكتروني',
      'ca': 'Enviar email',
      'de': 'E-Mail senden',
      'en': 'Send email',
      'fr': 'Envoyer un e-mail',
      'it': 'Invia una email',
      'ja': 'メールを送る',
      'pt': 'Enviar email',
      'zh_Hans': '发电子邮件',
    },
    'd8bimp1m': {
      'es': 'Home',
      'ar': 'بيت',
      'ca': 'Home',
      'de': 'heim',
      'en': 'home',
      'fr': 'maison',
      'it': 'casa',
      'ja': '家',
      'pt': 'lar',
      'zh_Hans': '家',
    },
  },
  // PrivacyPolicy
  {
    'r1ozsab1': {
      'es': 'Política de Privacidad de ToGo',
      'ar': 'سياسة خصوصية توجو',
      'ca': 'Política de Privadesa de ToGo',
      'de': 'ToGo-Datenschutzrichtlinie',
      'en': 'ToGo Privacy Policy',
      'fr': 'Politique de confidentialité de ToGo',
      'it': 'Informativa sulla privacy di ToGo',
      'ja': 'ToGo プライバシー ポリシー',
      'pt': 'Política de privacidade do ToGo',
      'zh_Hans': '多哥隐私政策',
    },
    '7bxo7d35': {
      'es':
          'Esta Política de Privacidad describe cómo ToGo (\"nosotros\", \"nuestro\" o \"la aplicación\") recopila, utiliza y comparte información personal cuando utilizas nuestra aplicación móvil ToGo (la \"Aplicación\"). Al utilizar la Aplicación, aceptas el tratamiento de tu información personal de acuerdo con esta Política de Privacidad.\n\nInformación que Recopilamos\n\nCuando utilizas nuestra Aplicación, podemos recopilar y procesar la siguiente información:\n\nInformación que nos proporcionas: Podemos recopilar la información que nos proporcionas voluntariamente al registrarte en la Aplicación, como tu nombre, dirección de correo electrónico, número de teléfono y preferencias de viaje.\n\nInformación de uso: Podemos recopilar información sobre cómo utilizas la Aplicación, como las páginas que visitas, las funciones que utilizas y la frecuencia con la que accedes a la Aplicación.\n\nInformación del dispositivo: Podemos recopilar información sobre tu dispositivo móvil, incluyendo el modelo del dispositivo, el sistema operativo, identificadores únicos del dispositivo y datos de la red móvil.\n\nCómo Utilizamos tu Información\n\nUtilizamos la información recopilada para los siguientes propósitos:\n\nPara proporcionarte los servicios y funciones de la Aplicación.\nPara personalizar tu experiencia y ofrecerte contenido y recomendaciones relevantes.\nPara comunicarnos contigo y responder a tus consultas y solicitudes.\nPara mejorar y optimizar nuestra Aplicación y desarrollar nuevos productos y servicios.\nPara fines de análisis y estadísticas.\nCompartir tu Información\n\nNo compartiremos tu información personal con terceros sin tu consentimiento, excepto en las siguientes circunstancias:\n\nCuando sea necesario para proporcionarte los servicios solicitados, como hacer una reserva de viaje.\nCuando sea necesario para cumplir con la ley, una orden judicial o una solicitud legalmente válida de las autoridades.\nCuando sea necesario para proteger nuestros derechos, propiedades o la seguridad de nuestros usuarios o del público en general.\nSeguridad de tu Información\n\nTomamos medidas razonables para proteger la información personal contra pérdida, robo, uso indebido, acceso no autorizado, divulgación, alteración y destrucción.\n\nCambios en esta Política de Privacidad\n\nPodemos actualizar esta Política de Privacidad de vez en cuando. Te recomendamos que revises periódicamente esta página para estar al tanto de cualquier cambio. La fecha de la última actualización se indicará al final de esta Política de Privacidad.\n\nCómo Contactarnos\n\nSi tienes alguna pregunta sobre esta Política de Privacidad, puedes contactarnos en [correo electrónico de contacto].\n\nÚltima actualización: 6 de marzo de 2024.',
      'ar':
          'تصف سياسة الخصوصية هذه كيفية قيام ToGo (\"نحن\" أو \"خاصتنا\" أو \"التطبيق\") بجمع المعلومات الشخصية واستخدامها ومشاركتها عند استخدام تطبيق ToGo للهاتف المحمول الخاص بنا (\"التطبيق\"). باستخدام التطبيق، فإنك توافق على معالجة معلوماتك الشخصية وفقًا لسياسة الخصوصية هذه.\n\nالمعلومات التي نجمعها\n\nعندما تستخدم تطبيقنا، قد نقوم بجمع ومعالجة المعلومات التالية:\n\nالمعلومات التي تقدمها لنا: قد نقوم بجمع المعلومات التي تقدمها لنا طوعًا عند التسجيل في التطبيق، مثل اسمك وعنوان بريدك الإلكتروني ورقم هاتفك وتفضيلات السفر.\n\nمعلومات الاستخدام: قد نقوم بجمع معلومات حول كيفية استخدامك للتطبيق، مثل الصفحات التي تزورها، والميزات التي تستخدمها، وعدد مرات وصولك إلى التطبيق.\n\nمعلومات الجهاز: قد نقوم بجمع معلومات حول جهازك المحمول، بما في ذلك طراز الجهاز ونظام التشغيل ومعرفات الجهاز الفريدة وبيانات شبكة الهاتف المحمول.\n\nكيف نستخدم معلوماتك\n\nنحن نستخدم المعلومات التي تم جمعها للأغراض التالية:\n\nلتزويدك بخدمات ووظائف التطبيق.\nلتخصيص تجربتك وتقديم المحتوى والتوصيات ذات الصلة لك.\nللتواصل معكم والرد على أسئلتكم وطلباتكم.\nلتحسين وتحسين تطبيقنا وتطوير منتجات وخدمات جديدة.\nلأغراض التحليل والإحصاءات.\nشارك معلوماتك\n\nلن نشارك معلوماتك الشخصية مع أطراف ثالثة دون موافقتك، إلا في الحالات التالية:\n\nعند الضرورة لتزويدك بالخدمات المطلوبة، مثل إجراء حجز السفر.\nعندما يكون ذلك ضروريًا للامتثال للقانون أو لأمر من المحكمة أو طلب صالح قانونًا من السلطات.\nعند الضرورة لحماية حقوقنا أو ممتلكاتنا أو سلامة مستخدمينا أو عامة الناس.\nأمن المعلومات الخاصة بك\n\nنحن نتخذ تدابير معقولة لحماية المعلومات الشخصية من الضياع والسرقة وسوء الاستخدام والوصول غير المصرح به والكشف والتغيير والتدمير.\n\nالتغييرات على سياسة الخصوصية هذه\n\nقد نقوم بتحديث سياسة الخصوصية هذه من وقت لآخر. ننصحك بمراجعة هذه الصفحة بشكل دوري لتكون على علم بأي تغييرات. سيتم الإشارة إلى تاريخ آخر تحديث في نهاية سياسة الخصوصية هذه.\n\nكيف تتواصل معنا\n\nإذا كانت لديك أي أسئلة حول سياسة الخصوصية هذه، يمكنك الاتصال بنا على [contact email].\n\nآخر تحديث: [تاريخ آخر تحديث لسياسة الخصوصية].',
      'ca':
          'Aquesta Política de Privadesa descriu com ToGo (\"nosaltres\", \"nostre\" o \"l\'aplicació\") recopila, utilitza i comparteix informació personal quan utilitzes la nostra aplicació mòbil ToGo (l\'\"Aplicació\"). En utilitzar l\'Aplicació, accepteu el tractament de la vostra informació personal d\'acord amb aquesta Política de Privadesa.\n\nInformació que Recopilem\n\nQuan utilitzes la nostra Aplicació, podem recopilar i processar la informació següent:\n\nInformació que ens proporciones: Podem recopilar la informació que ens proporciones voluntàriament en registrar-te a l\'Aplicació, com ara el teu nom, adreça de correu electrònic, número de telèfon i preferències de viatge.\n\nInformació d\'ús: Podem recopilar informació sobre com utilitzes l\'Aplicació, com ara les pàgines que visites, les funcions que utilitzes i la freqüència amb què accedeixes a l\'Aplicació.\n\nInformació del dispositiu: Podem recopilar informació sobre el vostre dispositiu mòbil, incloent-hi el model del dispositiu, el sistema operatiu, identificadors únics del dispositiu i dades de la xarxa mòbil.\n\nCom Utilitzem la teva Informació\n\nUtilitzem la informació recopilada per als següents propòsits:\n\nPer proporcionar-vos els serveis i les funcions de l\'Aplicació.\nPer personalitzar la teva experiència i oferir contingut i recomanacions rellevants.\nPer comunicar-nos amb tu i respondre les teves consultes i sol·licituds.\nPer millorar i optimitzar la nostra Aplicació i desenvolupar nous productes i serveis.\nPer a finalitats danàlisi i estadístiques.\nCompartir la teva informació\n\nNo compartirem la teva informació personal amb tercers sense el teu consentiment, excepte en les circumstàncies següents:\n\nQuan sigui necessari per proporcionar-te els serveis sol·licitats, com fer una reserva de viatge.\nQuan sigui necessari per complir amb la llei, una ordre judicial o una sol·licitud legalment vàlida de les autoritats.\nQuan sigui necessari per protegir els nostres drets, propietats o seguretat dels nostres usuaris o del públic en general.\nSeguretat de la teva informació\n\nPrenem mesures raonables per protegir la informació personal contra pèrdua, robatori, ús indegut, accés no autoritzat, divulgació, alteració i destrucció.\n\nCanvis en aquesta Política de Privadesa\n\nPodem actualitzar aquesta Política de Privadesa de tant en tant. Et recomanem que revisis periòdicament aquesta pàgina per estar al corrent de qualsevol canvi. La data de la darrera actualització s\'indicarà al final d\'aquesta Política de Privadesa.\n\nCom contactar-nos\n\nSi tens alguna pregunta sobre aquesta Política de Privadesa, pots contactar-nos a [correu electrònic de contacte].\n\nDarrera actualització: [data de la darrera actualització de la Política de Privadesa].',
      'de':
          'Diese Datenschutzrichtlinie beschreibt, wie ToGo („wir“, „unser“ oder „die App“) personenbezogene Daten erhebt, verwendet und weitergibt, wenn Sie unsere mobile ToGo-Anwendung (die „Anwendung“) nutzen. Durch die Nutzung der Anwendung stimmen Sie der Verarbeitung Ihrer personenbezogenen Daten gemäß dieser Datenschutzrichtlinie zu.\n\nInformationen, die wir sammeln\n\nWenn Sie unsere Anwendung nutzen, erfassen und verarbeiten wir möglicherweise die folgenden Informationen:\n\nInformationen, die Sie uns zur Verfügung stellen: Wir erfassen möglicherweise Informationen, die Sie uns bei der Registrierung für die Anwendung freiwillig zur Verfügung stellen, wie z. B. Ihren Namen, Ihre E-Mail-Adresse, Telefonnummer und Reisepräferenzen.\n\nNutzungsinformationen: Wir erfassen möglicherweise Informationen darüber, wie Sie die Anwendung nutzen, z. B. die von Ihnen besuchten Seiten, die von Ihnen genutzten Funktionen und wie oft Sie auf die Anwendung zugreifen.\n\nGeräteinformationen: Wir erfassen möglicherweise Informationen über Ihr Mobilgerät, einschließlich Gerätemodell, Betriebssystem, eindeutige Gerätekennungen und Mobilfunknetzdaten.\n\nWie wir Ihre Informationen verwenden\n\nWir verwenden die gesammelten Informationen für folgende Zwecke:\n\nUm Ihnen die Dienste und Funktionen der Anwendung bereitzustellen.\nUm Ihr Erlebnis zu personalisieren und Ihnen relevante Inhalte und Empfehlungen anzubieten.\nUm mit Ihnen zu kommunizieren und auf Ihre Fragen und Wünsche zu antworten.\nUm unsere Anwendung zu verbessern und zu optimieren und neue Produkte und Dienstleistungen zu entwickeln.\nFür Analyse- und Statistikzwecke.\nTeilen Sie Ihre Informationen\n\nWir geben Ihre persönlichen Daten nicht ohne Ihre Zustimmung an Dritte weiter, außer in den folgenden Fällen:\n\nWenn es erforderlich ist, um Ihnen die gewünschten Dienstleistungen bereitzustellen, z. B. eine Reisereservierung vorzunehmen.\nWenn es zur Einhaltung des Gesetzes, eines Gerichtsbeschlusses oder einer rechtsgültigen Anfrage von Behörden erforderlich ist.\nWenn es zum Schutz unserer Rechte, unseres Eigentums oder der Sicherheit unserer Benutzer oder der Öffentlichkeit erforderlich ist.\nSicherheit Ihrer Informationen\n\nWir ergreifen angemessene Maßnahmen, um personenbezogene Daten vor Verlust, Diebstahl, Missbrauch, unbefugtem Zugriff, Offenlegung, Änderung und Zerstörung zu schützen.\n\nÄnderungen dieser Datenschutzrichtlinie\n\nWir können diese Datenschutzrichtlinie von Zeit zu Zeit aktualisieren. Wir empfehlen Ihnen, diese Seite regelmäßig zu überprüfen, um über etwaige Änderungen informiert zu sein. Das Datum der letzten Aktualisierung wird am Ende dieser Datenschutzrichtlinie angegeben.\n\nWie Sie uns erreichen\n\nWenn Sie Fragen zu dieser Datenschutzrichtlinie haben, können Sie uns unter [Kontakt-E-Mail] kontaktieren.\n\nLetzte Aktualisierung: [Datum der letzten Aktualisierung der Datenschutzrichtlinie].',
      'en':
          'This Privacy Policy describes how ToGo (\"we\", \"our\" or \"the app\") collects, uses and shares personal information when you use our ToGo mobile application (the \"Application\"). By using the Application, you agree to the processing of your personal information in accordance with this Privacy Policy.\n\nInformation We Collect\n\nWhen you use our Application, we may collect and process the following information:\n\nInformation You Provide to Us: We may collect information that you voluntarily provide to us when registering with the Application, such as your name, email address, telephone number, and travel preferences.\n\nUsage Information: We may collect information about how you use the Application, such as the pages you visit, the features you use, and how often you access the Application.\n\nDevice Information: We may collect information about your mobile device, including device model, operating system, unique device identifiers, and mobile network data.\n\nHow We Use Your Information\n\nWe use the information collected for the following purposes:\n\nTo provide you with the services and functions of the Application.\nTo personalize your experience and offer you relevant content and recommendations.\nTo communicate with you and respond to your questions and requests.\nTo improve and optimize our Application and develop new products and services.\nFor analysis and statistics purposes.\nShare your Information\n\nWe will not share your personal information with third parties without your consent, except in the following circumstances:\n\nWhen necessary to provide you with requested services, such as making a travel reservation.\nWhen necessary to comply with the law, a court order or a legally valid request from authorities.\nWhen necessary to protect our rights, properties or the safety of our users or the general public.\nSecurity of your Information\n\nWe take reasonable measures to protect personal information from loss, theft, misuse, unauthorized access, disclosure, alteration and destruction.\n\nChanges to this Privacy Policy\n\nWe may update this Privacy Policy from time to time. We recommend that you periodically review this page to be aware of any changes. The date of the last update will be indicated at the end of this Privacy Policy.\n\nHow to Contact Us\n\nIf you have any questions about this Privacy Policy, you can contact us at [contact email].\n\nLast update: [date of the last update of the Privacy Policy].',
      'fr':
          'Cette politique de confidentialité décrit comment ToGo (« nous », « notre » ou « l\'application ») collecte, utilise et partage des informations personnelles lorsque vous utilisez notre application mobile ToGo (l\'« Application »). En utilisant l\'Application, vous acceptez le traitement de vos informations personnelles conformément à la présente Politique de confidentialité.\n\nInformations que nous collectons\n\nLorsque vous utilisez notre Application, nous pouvons collecter et traiter les informations suivantes :\n\nInformations que vous nous fournissez : Nous pouvons collecter des informations que vous nous fournissez volontairement lors de votre inscription à l\'Application, telles que votre nom, votre adresse e-mail, votre numéro de téléphone et vos préférences de voyage.\n\nInformations d\'utilisation : nous pouvons collecter des informations sur la manière dont vous utilisez l\'Application, telles que les pages que vous visitez, les fonctionnalités que vous utilisez et la fréquence à laquelle vous accédez à l\'Application.\n\nInformations sur l\'appareil : nous pouvons collecter des informations sur votre appareil mobile, notamment le modèle de l\'appareil, le système d\'exploitation, les identifiants uniques de l\'appareil et les données du réseau mobile.\n\nComment nous utilisons vos informations\n\nNous utilisons les informations collectées aux fins suivantes :\n\nPour vous fournir les services et fonctions de l’Application.\nPour personnaliser votre expérience et vous proposer du contenu et des recommandations pertinentes.\nPour communiquer avec vous et répondre à vos questions et demandes.\nAméliorer et optimiser notre Application et développer de nouveaux produits et services.\nÀ des fins d’analyse et de statistiques.\nPartagez vos informations\n\nNous ne partagerons pas vos informations personnelles avec des tiers sans votre consentement, sauf dans les circonstances suivantes :\n\nLorsque cela est nécessaire pour vous fournir les services demandés, comme effectuer une réservation de voyage.\nLorsque cela est nécessaire pour se conformer à la loi, à une ordonnance du tribunal ou à une demande légalement valable des autorités.\nLorsque cela est nécessaire pour protéger nos droits, nos propriétés ou la sécurité de nos utilisateurs ou du grand public.\nSécurité de vos informations\n\nNous prenons des mesures raisonnables pour protéger les informations personnelles contre la perte, le vol, l\'utilisation abusive, l\'accès non autorisé, la divulgation, l\'altération et la destruction.\n\nModifications de cette politique de confidentialité\n\nNous pouvons mettre à jour cette politique de confidentialité de temps à autre. Nous vous recommandons de consulter périodiquement cette page pour être au courant de tout changement. La date de la dernière mise à jour sera indiquée à la fin de la présente Politique de Confidentialité.\n\nComment nous contacter\n\nSi vous avez des questions concernant cette politique de confidentialité, vous pouvez nous contacter à [e-mail de contact].\n\nDernière mise à jour : [date de la dernière mise à jour de la Politique de Confidentialité].',
      'it':
          'La presente Informativa sulla privacy descrive come ToGo (\"noi\", \"nostro\" o \"l\'app\") raccoglie, utilizza e condivide le informazioni personali quando utilizzi la nostra applicazione mobile ToGo (l\'\"Applicazione\"). Utilizzando l\'Applicazione, accetti il ​​trattamento dei tuoi dati personali in conformità con la presente Informativa sulla privacy.\n\nInformazioni che raccogliamo\n\nQuando utilizzi la nostra Applicazione, potremmo raccogliere ed elaborare le seguenti informazioni:\n\nInformazioni che ci fornisci: potremmo raccogliere informazioni che ci fornisci volontariamente al momento della registrazione all\'Applicazione, come nome, indirizzo email, numero di telefono e preferenze di viaggio.\n\nInformazioni sull\'utilizzo: potremmo raccogliere informazioni su come utilizzi l\'Applicazione, come le pagine che visiti, le funzionalità che utilizzi e la frequenza con cui accedi all\'Applicazione.\n\nInformazioni sul dispositivo: potremmo raccogliere informazioni sul tuo dispositivo mobile, inclusi modello del dispositivo, sistema operativo, identificatori univoci del dispositivo e dati della rete mobile.\n\nCome utilizziamo le tue informazioni\n\nUtilizziamo le informazioni raccolte per i seguenti scopi:\n\nPer fornirti i servizi e le funzioni dell\'Applicazione.\nPer personalizzare la tua esperienza e offrirti contenuti e consigli pertinenti.\nPer comunicare con te e rispondere alle tue domande e richieste.\nPer migliorare e ottimizzare la nostra Applicazione e sviluppare nuovi prodotti e servizi.\nPer scopi di analisi e statistica.\nCondividi le tue informazioni\n\nNon condivideremo le tue informazioni personali con terzi senza il tuo consenso, tranne nelle seguenti circostanze:\n\nQuando necessario per fornirti i servizi richiesti, come effettuare una prenotazione di viaggio.\nQuando necessario per rispettare la legge, un ordine del tribunale o una richiesta legalmente valida delle autorità.\nQuando necessario per proteggere i nostri diritti, le nostre proprietà o la sicurezza dei nostri utenti o del pubblico in generale.\nSicurezza delle tue informazioni\n\nAdottiamo misure ragionevoli per proteggere le informazioni personali da perdita, furto, uso improprio, accesso non autorizzato, divulgazione, alterazione e distruzione.\n\nModifiche alla presente Informativa sulla privacy\n\nPotremmo aggiornare la presente Informativa sulla privacy di tanto in tanto. Ti consigliamo di rivedere periodicamente questa pagina per essere a conoscenza di eventuali modifiche. La data dell\'ultimo aggiornamento sarà indicata in fondo alla presente Privacy Policy.\n\nCome contattarci\n\nIn caso di domande sulla presente Informativa sulla privacy, è possibile contattarci all\'indirizzo [e-mail di contatto].\n\nUltimo aggiornamento: [data dell\'ultimo aggiornamento della Privacy Policy].',
      'ja':
          'このプライバシー ポリシーでは、ToGo モバイル アプリケーション (「アプリケーション」) を使用する際に、ToGo (「当社」、「当社の」、または「アプリ」) が個人情報をどのように収集、使用、および共有するかについて説明します。アプリケーションを使用すると、このプライバシー ポリシーに従って個人情報が処理されることに同意したものとみなされます。\n\n当社が収集する情報\n\nお客様が当社のアプリケーションを使用する場合、当社は次の情報を収集して処理する場合があります。\n\nお客様が当社に提供する情報：当社は、お客様の名前、電子メールアドレス、電話番号、旅行の希望など、アプリケーションに登録する際にお客様が自発的に当社に提供した情報を収集する場合があります。\n\n使用状況情報: 当社は、アクセスしたページ、使用した機能、アプリケーションへのアクセス頻度など、アプリケーションの使用方法に関する情報を収集する場合があります。\n\nデバイス情報: 当社は、デバイスのモデル、オペレーティング システム、固有のデバイス識別子、モバイル ネットワーク データなど、お客様のモバイル デバイスに関する情報を収集する場合があります。\n\nお客様の情報の使用方法\n\n当社は収集した情報を次の目的で使用します。\n\nアプリケーションのサービスと機能を提供するため。\nお客様のエクスペリエンスをパーソナライズし、関連するコンテンツや推奨事項を提供するため。\nお客様と連絡を取り、お客様の質問やリクエストに対応するため。\n当社のアプリケーションを改善および最適化し、新しい製品やサービスを開発するため。\n分析と統計の目的。\n情報を共有する\n\n当社は、以下の場合を除き、お客様の個人情報をお客様の同意なしに第三者と共有することはありません。\n\n旅行の予約など、リクエストされたサービスを提供するために必要な場合。\n法律、裁判所命令、または当局からの法的に有効な要求を遵守するために必要な場合。\n当社の権利、財産、ユーザーまたは一般大衆の安全を保護するために必要な場合。\nあなたの情報のセキュリティ\n\n当社は、個人情報を紛失、盗難、悪用、不正アクセス、開示、改ざんおよび破壊から保護するために合理的な措置を講じます。\n\nこのプライバシーポリシーの変更\n\n当社は、このプライバシー ポリシーを随時更新することがあります。このページを定期的に確認して、変更を認識することをお勧めします。最終更新日は、このプライバシー ポリシーの最後に記載されています。\n\nお問い合わせ方法\n\nこのプライバシー ポリシーについてご質問がある場合は、[連絡先メールアドレス] までご連絡ください。\n\n最終更新日: [プライバシー ポリシーの最終更新日]。',
      'pt':
          'Esta Política de Privacidade descreve como o ToGo (\"nós\", \"nosso\" ou \"o aplicativo\") coleta, usa e compartilha informações pessoais quando você usa nosso aplicativo móvel ToGo (o \"Aplicativo\"). Ao utilizar o Aplicativo, você concorda com o processamento de suas informações pessoais de acordo com esta Política de Privacidade.\n\nInformações que coletamos\n\nQuando você usa nosso Aplicativo, podemos coletar e processar as seguintes informações:\n\nInformações que você nos fornece: podemos coletar informações que você nos fornece voluntariamente ao se registrar no Aplicativo, como seu nome, endereço de e-mail, número de telefone e preferências de viagem.\n\nInformações de uso: Podemos coletar informações sobre como você usa o Aplicativo, como as páginas que você visita, os recursos que você usa e com que frequência você acessa o Aplicativo.\n\nInformações do dispositivo: podemos coletar informações sobre o seu dispositivo móvel, incluindo modelo do dispositivo, sistema operacional, identificadores exclusivos do dispositivo e dados da rede móvel.\n\nComo usamos suas informações\n\nUtilizamos as informações coletadas para os seguintes fins:\n\nPara fornecer a você os serviços e funções do Aplicativo.\nPara personalizar sua experiência e oferecer conteúdos e recomendações relevantes.\nPara comunicar consigo e responder às suas perguntas e pedidos.\nPara melhorar e otimizar nosso Aplicativo e desenvolver novos produtos e serviços.\nPara fins de análise e estatística.\nCompartilhe suas informações\n\nNão compartilharemos suas informações pessoais com terceiros sem o seu consentimento, exceto nas seguintes circunstâncias:\n\nQuando necessário para lhe fornecer os serviços solicitados, como fazer uma reserva de viagem.\nQuando necessário para cumprir a lei, uma ordem judicial ou uma solicitação legalmente válida das autoridades.\nQuando necessário para proteger os nossos direitos, propriedades ou a segurança dos nossos utilizadores ou do público em geral.\nSegurança das suas informações\n\nTomamos medidas razoáveis ​​para proteger as informações pessoais contra perda, roubo, uso indevido, acesso não autorizado, divulgação, alteração e destruição.\n\nAlterações nesta Política de Privacidade\n\nPoderemos atualizar esta Política de Privacidade de tempos em tempos. Recomendamos que você revise periodicamente esta página para estar ciente de quaisquer alterações. A data da última atualização será indicada no final desta Política de Privacidade.\n\nComo entrar em contato conosco\n\nSe você tiver alguma dúvida sobre esta Política de Privacidade, entre em contato conosco pelo e-mail [e-mail de contato].\n\nÚltima atualização: [data da última atualização da Política de Privacidade].',
      'zh_Hans':
          '本隐私政策描述了当您使用我们的 ToGo 移动应用程序（“应用程序”）时，ToGo（“我们”、“我们的”或“应用程序”）如何收集、使用和共享个人信息。使用该应用程序，即表示您同意根据本隐私政策处理您的个人信息。\n\n我们收集的信息\n\n当您使用我们的应用程序时，我们可能会收集和处理以下信息：\n\n您向我们提供的信息：我们可能会收集您在注册应用程序时自愿向我们提供的信息，例如您的姓名、电子邮件地址、电话号码和旅行偏好。\n\n使用信息：我们可能会收集有关您如何使用应用程序的信息，例如您访问的页面、您使用的功能以及您访问应用程序的频率。\n\n设备信息：我们可能会收集有关您的移动设备的信息，包括设备型号、操作系统、唯一设备标识符和移动网络数据。\n\n我们如何使用您的信息\n\n我们将收集的信息用于以下目的：\n\n为您提供应用程序的服务和功能。\n个性化您的体验并为您提供相关内容和建议。\n与您沟通并回答您的问题和请求。\n改进和优化我们的应用程序并开发新产品和服务。\n用于分析和统计目的。\n分享您的信息\n\n未经您的同意，我们不会与第三方共享您的个人信息，但以下情况除外：\n\n必要时向您提供所要求的服务，例如旅行预订。\n当有必要遵守法律、法院命令或当局的合法有效要求时。\n当有必要保护我们的权利、财产或我们的用户或公众的安全时。\n您的信息安全\n\n我们采取合理措施保护个人信息免遭丢失、盗窃、滥用、未经授权的访问、披露、更改和破坏。\n\n本隐私政策的变更\n\n我们可能会不时更新本隐私政策。我们建议您定期查看此页面以了解任何更改。最后更新日期将在本隐私政策末尾注明。\n\n如何联系我们\n\n如果您对本隐私政策有任何疑问，您可以通过[联系电子邮件]与我们联系。\n\n最后更新：[隐私政策最后更新的日期]。',
    },
    '26kuln50': {
      'es': 'Política de Privacidad',
      'ar': 'سياسة الخصوصية',
      'ca': 'Política de Privadesa',
      'de': 'Datenschutzrichtlinie',
      'en': 'Privacy Policy',
      'fr': 'Politique de confidentialité',
      'it': 'politica sulla riservatezza',
      'ja': 'プライバシーポリシー',
      'pt': 'Política de privacidade',
      'zh_Hans': '隐私政策',
    },
    'vk3ou2x2': {
      'es': 'Home',
      'ar': 'بيت',
      'ca': 'Home',
      'de': 'heim',
      'en': 'home',
      'fr': 'maison',
      'it': 'casa',
      'ja': '家',
      'pt': 'lar',
      'zh_Hans': '家',
    },
  },
  // ForgottenPassword2
  {
    'xu0i7aut': {
      'es': 'Nueva\ncontraseña',
      'ar': 'جديد\nكلمة المرور',
      'ca': 'Nova\ncontrasenya',
      'de': 'Neu\nPasswort',
      'en': 'New\npassword',
      'fr': 'Nouveau\nmot de passe',
      'it': 'Nuovo\nparola d\'ordine',
      'ja': '新しい\nパスワード',
      'pt': 'Novo\nsenha',
      'zh_Hans': '新的\n密码',
    },
    'ux2wogll': {
      'es': 'Nueva contraseña',
      'ar': 'كلمة المرور الجديدة',
      'ca': 'Nova contrasenya',
      'de': 'Neues Kennwort',
      'en': 'New Password',
      'fr': 'nouveau mot de passe',
      'it': 'nuova password',
      'ja': '新しいパスワード',
      'pt': 'Nova senha',
      'zh_Hans': '新密码',
    },
    '8t2auogd': {
      'es': 'Confirmar contraseña',
      'ar': 'كرر كلمة المرور الجديدة',
      'ca': 'Repetir una contrasenya nova',
      'de': 'Wiederhole das neue Passwort',
      'en': 'Repeat new password',
      'fr': 'Répété le nouveau mot de passe',
      'it': 'ripetere la nuova password',
      'ja': '新しいパスワードを繰り返します',
      'pt': 'Repita a nova senha',
      'zh_Hans': '重复新密码',
    },
    'tm8tmq13': {
      'es': 'Restablecer',
      'ar': 'يعيد',
      'ca': 'Restablir',
      'de': 'Wiederherstellen',
      'en': 'Restore',
      'fr': 'Restaurer',
      'it': 'Ristabilire',
      'ja': '復元する',
      'pt': 'Restaurar',
      'zh_Hans': '恢复',
    },
    'kcq60rqq': {
      'es': 'Home',
      'ar': 'بيت',
      'ca': 'Home',
      'de': 'heim',
      'en': 'home',
      'fr': 'maison',
      'it': 'casa',
      'ja': '家',
      'pt': 'lar',
      'zh_Hans': '家',
    },
  },
  // Language
  {
    '3wk51o56': {
      'es': 'Español',
      'ar': 'الأسبانية',
      'ca': 'Espanyol',
      'de': 'Spanisch',
      'en': 'Spanish',
      'fr': 'Espagnol',
      'it': 'spagnolo',
      'ja': 'スペイン語',
      'pt': 'Espanhol',
      'zh_Hans': '西班牙语',
    },
    'a5cy3mkb': {
      'es': 'Español',
      'ar': 'الأسبانية',
      'ca': 'Espanyol',
      'de': 'Spanisch',
      'en': 'Spanish',
      'fr': 'Espagnol',
      'it': 'spagnolo',
      'ja': 'スペイン語',
      'pt': 'Espanhol',
      'zh_Hans': '西班牙语',
    },
    'hu3zi4mj': {
      'es': 'Català',
      'ar': 'Català',
      'ca': 'Català',
      'de': 'Català',
      'en': 'Català',
      'fr': 'Català',
      'it': 'Català',
      'ja': 'Català',
      'pt': 'Català',
      'zh_Hans': 'Català',
    },
    'nkp6tmb5': {
      'es': 'Catalán',
      'ar': 'الكاتالونية',
      'ca': 'Català',
      'de': 'katalanisch',
      'en': 'Catalan',
      'fr': 'catalan',
      'it': 'catalano',
      'ja': 'カタルーニャ語',
      'pt': 'catalão',
      'zh_Hans': '加泰罗尼亚语',
    },
    '116a0o2y': {
      'es': 'English',
      'ar': 'English',
      'ca': 'English',
      'de': 'English',
      'en': 'English',
      'fr': 'English',
      'it': 'English',
      'ja': 'English',
      'pt': 'English',
      'zh_Hans': 'English',
    },
    'iykjxid9': {
      'es': 'Inglés',
      'ar': 'إنجليزي',
      'ca': 'Anglès',
      'de': 'Englisch',
      'en': 'English',
      'fr': 'Anglais',
      'it': 'Inglese',
      'ja': '英語',
      'pt': 'Inglês',
      'zh_Hans': '英语',
    },
    '3rapt36v': {
      'es': 'Français',
      'ar': 'Français',
      'ca': 'Français',
      'de': 'Français',
      'en': 'Français',
      'fr': 'Français',
      'it': 'Français',
      'ja': 'Français',
      'pt': 'Français',
      'zh_Hans': 'Français',
    },
    's21jq2na': {
      'es': 'Francés',
      'ar': 'فرنسي',
      'ca': 'Francès',
      'de': 'Französisch',
      'en': 'French',
      'fr': 'Français',
      'it': 'francese',
      'ja': 'フランス語',
      'pt': 'Francês',
      'zh_Hans': '法语',
    },
    'suydd9lv': {
      'es': 'Deutsch',
      'ar': 'Deutsch',
      'ca': 'Deutsch',
      'de': 'Deutsch',
      'en': 'Deutsch',
      'fr': 'Deutsch',
      'it': 'Deutsch',
      'ja': 'Deutsch',
      'pt': 'Deutsch',
      'zh_Hans': 'Deutsch',
    },
    '1182866c': {
      'es': 'Alemán',
      'ar': 'ألمانية',
      'ca': 'Alemany',
      'de': 'Deutsch',
      'en': 'German',
      'fr': 'Allemand',
      'it': 'Tedesco',
      'ja': 'ドイツ人',
      'pt': 'Alemão',
      'zh_Hans': '德语',
    },
    'ht56ep7w': {
      'es': 'Italiano',
      'ar': 'Italiano',
      'ca': 'Italiano',
      'de': 'Italiano',
      'en': 'Italiano',
      'fr': 'Italiano',
      'it': 'Italiano',
      'ja': 'Italiano',
      'pt': 'Italiano',
      'zh_Hans': 'Italiano',
    },
    'k2ref3pu': {
      'es': 'Italiano',
      'ar': 'ايطالي',
      'ca': 'Italià',
      'de': 'Italienisch',
      'en': 'Italian',
      'fr': 'italien',
      'it': 'Italiano',
      'ja': 'イタリアの',
      'pt': 'italiano',
      'zh_Hans': '意大利语',
    },
    '7r6a8kuy': {
      'es': 'Português',
      'ar': 'Português',
      'ca': 'Português',
      'de': 'Português',
      'en': 'Português',
      'fr': 'Português',
      'it': 'Português',
      'ja': 'Português',
      'pt': 'Português',
      'zh_Hans': 'Português',
    },
    '0ngdak9t': {
      'es': 'Portugués',
      'ar': 'البرتغالية',
      'ca': 'Portuguès',
      'de': 'Portugiesisch',
      'en': 'Portuguese',
      'fr': 'Portugais',
      'it': 'portoghese',
      'ja': 'ポルトガル語',
      'pt': 'Português',
      'zh_Hans': '葡萄牙语',
    },
    'i6eujnca': {
      'es': 'العربية',
      'ar': 'العربية',
      'ca': 'العربية',
      'de': 'العربية',
      'en': 'العربية',
      'fr': 'العربية',
      'it': 'العربية',
      'ja': 'العربية',
      'pt': 'العربية',
      'zh_Hans': 'العربية',
    },
    '86peemmj': {
      'es': 'Árabe',
      'ar': 'عرب',
      'ca': 'Àrab',
      'de': 'Araber',
      'en': 'Arab',
      'fr': 'arabe',
      'it': 'arabo',
      'ja': 'アラブ',
      'pt': 'árabe',
      'zh_Hans': '阿拉伯',
    },
    'jsfzhqk8': {
      'es': 'Idioma',
      'ar': 'لغة',
      'ca': 'Idioma',
      'de': 'Sprache',
      'en': 'Language',
      'fr': 'langage',
      'it': 'Lingua',
      'ja': '言語',
      'pt': 'Linguagem',
      'zh_Hans': '语言',
    },
    'egdcncxu': {
      'es': 'Home',
      'ar': 'بيت',
      'ca': 'Home',
      'de': 'heim',
      'en': 'home',
      'fr': 'maison',
      'it': 'casa',
      'ja': '家',
      'pt': 'lar',
      'zh_Hans': '家',
    },
  },
  // TermsConditions
  {
    'k8579xz7': {
      'es': 'Términos y Condiciones de Uso de ToGo',
      'ar': 'سياسة خصوصية توجو',
      'ca': 'Política de Privadesa de ToGo',
      'de': 'ToGo-Datenschutzrichtlinie',
      'en': 'ToGo Privacy Policy',
      'fr': 'Politique de confidentialité de ToGo',
      'it': 'Informativa sulla privacy di ToGo',
      'ja': 'ToGo プライバシー ポリシー',
      'pt': 'Política de privacidade do ToGo',
      'zh_Hans': '多哥隐私政策',
    },
    'wtixw79u': {
      'es':
          'Estos términos y condiciones (\"Términos\") rigen el uso de la aplicación móvil ToGo (\"la Aplicación\") y cualquier servicio proporcionado por ToGo (\"el Servicio\"). Al acceder y utilizar la Aplicación y el Servicio, aceptas estar legalmente obligado por estos Términos. Si no estás de acuerdo con alguno de estos términos, no uses la Aplicación ni el Servicio.\n\n1. Uso de la Aplicación\n\n1.1. Licencia: Se te concede una licencia limitada, no exclusiva, intransferible y revocable para usar la Aplicación con fines personales y no comerciales.\n\n1.2. Uso Adecuado: Debes usar la Aplicación de acuerdo con estos Términos, cualquier ley aplicable y los estándares aceptados de comportamiento en línea.\n\n1.3. Restricciones: No puedes modificar, adaptar, traducir, realizar ingeniería inversa, descompilar ni desensamblar la Aplicación.\n\n2. Cuentas de Usuario\n\n2.1. Registro: Al registrarte para usar la Aplicación, aceptas proporcionar información precisa, completa y actualizada sobre ti mismo según lo solicitado en el proceso de registro.\n\n2.2. Seguridad de la Cuenta: Eres responsable de mantener la seguridad de tu cuenta y contraseña. No debes compartir tu contraseña con terceros.\n\n2.3. Uso no autorizado: Debes notificar de inmediato a ToGo cualquier uso no autorizado de tu cuenta o cualquier otra violación de seguridad.\n\n3. Contenido del Usuario\n\n3.1. Responsabilidad del Usuario: Eres completamente responsable del contenido que compartas a través de la Aplicación.\n\n3.2. Derechos de ToGo: ToGo se reserva el derecho de eliminar cualquier contenido que considere inapropiado o que viole estos Términos.\n\n4. Privacidad\n\n4.1. Política de Privacidad: El uso de la Aplicación y del Servicio está sujeto a nuestra Política de Privacidad, que se puede encontrar en [enlace a la política de privacidad].\n\n5. Modificaciones\n\n5.1. Cambios en los Términos: ToGo se reserva el derecho de modificar estos Términos en cualquier momento. Los cambios entrarán en vigencia inmediatamente después de su publicación en la Aplicación.\n\n6. Limitación de Responsabilidad\n\n6.1. Exención de Responsabilidad: En la medida máxima permitida por la ley, ToGo no será responsable de ningún daño directo, indirecto, incidental, especial, consecuente o punitivo que surja del uso de la Aplicación o del Servicio.\n\n7. Ley Aplicable\n\n7.1. Jurisdicción: Estos Términos se regirán e interpretarán de acuerdo con las leyes del [país o región] sin tener en cuenta sus disposiciones sobre conflictos de leyes.\n\n8. Contacto\n\n8.1. Atención al Cliente: Si tienes alguna pregunta sobre estos Términos, puedes contactar con nosotros en [dirección de correo electrónico].\n\nAl usar la Aplicación y el Servicio, aceptas cumplir con estos Términos. Si no estás de acuerdo con estos Términos, por favor, no uses la Aplicación ni el Servicio.\n\nÚltima actualización: 6 de marzo de 2024',
      'ar':
          'تصف سياسة الخصوصية هذه كيفية قيام ToGo (\"نحن\" أو \"خاصتنا\" أو \"التطبيق\") بجمع المعلومات الشخصية واستخدامها ومشاركتها عند استخدام تطبيق ToGo للهاتف المحمول الخاص بنا (\"التطبيق\"). باستخدام التطبيق، فإنك توافق على معالجة معلوماتك الشخصية وفقًا لسياسة الخصوصية هذه.\n\nالمعلومات التي نجمعها\n\nعندما تستخدم تطبيقنا، قد نقوم بجمع ومعالجة المعلومات التالية:\n\nالمعلومات التي تقدمها لنا: قد نقوم بجمع المعلومات التي تقدمها لنا طوعًا عند التسجيل في التطبيق، مثل اسمك وعنوان بريدك الإلكتروني ورقم هاتفك وتفضيلات السفر.\n\nمعلومات الاستخدام: قد نقوم بجمع معلومات حول كيفية استخدامك للتطبيق، مثل الصفحات التي تزورها، والميزات التي تستخدمها، وعدد مرات وصولك إلى التطبيق.\n\nمعلومات الجهاز: قد نقوم بجمع معلومات حول جهازك المحمول، بما في ذلك طراز الجهاز ونظام التشغيل ومعرفات الجهاز الفريدة وبيانات شبكة الهاتف المحمول.\n\nكيف نستخدم معلوماتك\n\nنحن نستخدم المعلومات التي تم جمعها للأغراض التالية:\n\nلتزويدك بخدمات ووظائف التطبيق.\nلتخصيص تجربتك وتقديم المحتوى والتوصيات ذات الصلة لك.\nللتواصل معكم والرد على أسئلتكم وطلباتكم.\nلتحسين وتحسين تطبيقنا وتطوير منتجات وخدمات جديدة.\nلأغراض التحليل والإحصاءات.\nشارك معلوماتك\n\nلن نشارك معلوماتك الشخصية مع أطراف ثالثة دون موافقتك، إلا في الحالات التالية:\n\nعند الضرورة لتزويدك بالخدمات المطلوبة، مثل إجراء حجز السفر.\nعندما يكون ذلك ضروريًا للامتثال للقانون أو لأمر من المحكمة أو طلب صالح قانونًا من السلطات.\nعند الضرورة لحماية حقوقنا أو ممتلكاتنا أو سلامة مستخدمينا أو عامة الناس.\nأمن المعلومات الخاصة بك\n\nنحن نتخذ تدابير معقولة لحماية المعلومات الشخصية من الضياع والسرقة وسوء الاستخدام والوصول غير المصرح به والكشف والتغيير والتدمير.\n\nالتغييرات على سياسة الخصوصية هذه\n\nقد نقوم بتحديث سياسة الخصوصية هذه من وقت لآخر. ننصحك بمراجعة هذه الصفحة بشكل دوري لتكون على علم بأي تغييرات. سيتم الإشارة إلى تاريخ آخر تحديث في نهاية سياسة الخصوصية هذه.\n\nكيف تتواصل معنا\n\nإذا كانت لديك أي أسئلة حول سياسة الخصوصية هذه، يمكنك الاتصال بنا على [contact email].\n\nآخر تحديث: [تاريخ آخر تحديث لسياسة الخصوصية].',
      'ca':
          'Aquesta Política de Privadesa descriu com ToGo (\"nosaltres\", \"nostre\" o \"l\'aplicació\") recopila, utilitza i comparteix informació personal quan utilitzes la nostra aplicació mòbil ToGo (l\'\"Aplicació\"). En utilitzar l\'Aplicació, accepteu el tractament de la vostra informació personal d\'acord amb aquesta Política de Privadesa.\n\nInformació que Recopilem\n\nQuan utilitzes la nostra Aplicació, podem recopilar i processar la informació següent:\n\nInformació que ens proporciones: Podem recopilar la informació que ens proporciones voluntàriament en registrar-te a l\'Aplicació, com ara el teu nom, adreça de correu electrònic, número de telèfon i preferències de viatge.\n\nInformació d\'ús: Podem recopilar informació sobre com utilitzes l\'Aplicació, com ara les pàgines que visites, les funcions que utilitzes i la freqüència amb què accedeixes a l\'Aplicació.\n\nInformació del dispositiu: Podem recopilar informació sobre el vostre dispositiu mòbil, incloent-hi el model del dispositiu, el sistema operatiu, identificadors únics del dispositiu i dades de la xarxa mòbil.\n\nCom Utilitzem la teva Informació\n\nUtilitzem la informació recopilada per als següents propòsits:\n\nPer proporcionar-vos els serveis i les funcions de l\'Aplicació.\nPer personalitzar la teva experiència i oferir contingut i recomanacions rellevants.\nPer comunicar-nos amb tu i respondre les teves consultes i sol·licituds.\nPer millorar i optimitzar la nostra Aplicació i desenvolupar nous productes i serveis.\nPer a finalitats danàlisi i estadístiques.\nCompartir la teva informació\n\nNo compartirem la teva informació personal amb tercers sense el teu consentiment, excepte en les circumstàncies següents:\n\nQuan sigui necessari per proporcionar-te els serveis sol·licitats, com fer una reserva de viatge.\nQuan sigui necessari per complir amb la llei, una ordre judicial o una sol·licitud legalment vàlida de les autoritats.\nQuan sigui necessari per protegir els nostres drets, propietats o seguretat dels nostres usuaris o del públic en general.\nSeguretat de la teva informació\n\nPrenem mesures raonables per protegir la informació personal contra pèrdua, robatori, ús indegut, accés no autoritzat, divulgació, alteració i destrucció.\n\nCanvis en aquesta Política de Privadesa\n\nPodem actualitzar aquesta Política de Privadesa de tant en tant. Et recomanem que revisis periòdicament aquesta pàgina per estar al corrent de qualsevol canvi. La data de la darrera actualització s\'indicarà al final d\'aquesta Política de Privadesa.\n\nCom contactar-nos\n\nSi tens alguna pregunta sobre aquesta Política de Privadesa, pots contactar-nos a [correu electrònic de contacte].\n\nDarrera actualització: [data de la darrera actualització de la Política de Privadesa].',
      'de':
          'Diese Datenschutzrichtlinie beschreibt, wie ToGo („wir“, „unser“ oder „die App“) personenbezogene Daten erhebt, verwendet und weitergibt, wenn Sie unsere mobile ToGo-Anwendung (die „Anwendung“) nutzen. Durch die Nutzung der Anwendung stimmen Sie der Verarbeitung Ihrer personenbezogenen Daten gemäß dieser Datenschutzrichtlinie zu.\n\nInformationen, die wir sammeln\n\nWenn Sie unsere Anwendung nutzen, erfassen und verarbeiten wir möglicherweise die folgenden Informationen:\n\nInformationen, die Sie uns zur Verfügung stellen: Wir erfassen möglicherweise Informationen, die Sie uns bei der Registrierung für die Anwendung freiwillig zur Verfügung stellen, wie z. B. Ihren Namen, Ihre E-Mail-Adresse, Telefonnummer und Reisepräferenzen.\n\nNutzungsinformationen: Wir erfassen möglicherweise Informationen darüber, wie Sie die Anwendung nutzen, z. B. die von Ihnen besuchten Seiten, die von Ihnen genutzten Funktionen und wie oft Sie auf die Anwendung zugreifen.\n\nGeräteinformationen: Wir erfassen möglicherweise Informationen über Ihr Mobilgerät, einschließlich Gerätemodell, Betriebssystem, eindeutige Gerätekennungen und Mobilfunknetzdaten.\n\nWie wir Ihre Informationen verwenden\n\nWir verwenden die gesammelten Informationen für folgende Zwecke:\n\nUm Ihnen die Dienste und Funktionen der Anwendung bereitzustellen.\nUm Ihr Erlebnis zu personalisieren und Ihnen relevante Inhalte und Empfehlungen anzubieten.\nUm mit Ihnen zu kommunizieren und auf Ihre Fragen und Wünsche zu antworten.\nUm unsere Anwendung zu verbessern und zu optimieren und neue Produkte und Dienstleistungen zu entwickeln.\nFür Analyse- und Statistikzwecke.\nTeilen Sie Ihre Informationen\n\nWir geben Ihre persönlichen Daten nicht ohne Ihre Zustimmung an Dritte weiter, außer in den folgenden Fällen:\n\nWenn es erforderlich ist, um Ihnen die gewünschten Dienstleistungen bereitzustellen, z. B. eine Reisereservierung vorzunehmen.\nWenn es zur Einhaltung des Gesetzes, eines Gerichtsbeschlusses oder einer rechtsgültigen Anfrage von Behörden erforderlich ist.\nWenn es zum Schutz unserer Rechte, unseres Eigentums oder der Sicherheit unserer Benutzer oder der Öffentlichkeit erforderlich ist.\nSicherheit Ihrer Informationen\n\nWir ergreifen angemessene Maßnahmen, um personenbezogene Daten vor Verlust, Diebstahl, Missbrauch, unbefugtem Zugriff, Offenlegung, Änderung und Zerstörung zu schützen.\n\nÄnderungen dieser Datenschutzrichtlinie\n\nWir können diese Datenschutzrichtlinie von Zeit zu Zeit aktualisieren. Wir empfehlen Ihnen, diese Seite regelmäßig zu überprüfen, um über etwaige Änderungen informiert zu sein. Das Datum der letzten Aktualisierung wird am Ende dieser Datenschutzrichtlinie angegeben.\n\nWie Sie uns erreichen\n\nWenn Sie Fragen zu dieser Datenschutzrichtlinie haben, können Sie uns unter [Kontakt-E-Mail] kontaktieren.\n\nLetzte Aktualisierung: [Datum der letzten Aktualisierung der Datenschutzrichtlinie].',
      'en':
          'This Privacy Policy describes how ToGo (\"we\", \"our\" or \"the app\") collects, uses and shares personal information when you use our ToGo mobile application (the \"Application\"). By using the Application, you agree to the processing of your personal information in accordance with this Privacy Policy.\n\nInformation We Collect\n\nWhen you use our Application, we may collect and process the following information:\n\nInformation You Provide to Us: We may collect information that you voluntarily provide to us when registering with the Application, such as your name, email address, telephone number, and travel preferences.\n\nUsage Information: We may collect information about how you use the Application, such as the pages you visit, the features you use, and how often you access the Application.\n\nDevice Information: We may collect information about your mobile device, including device model, operating system, unique device identifiers, and mobile network data.\n\nHow We Use Your Information\n\nWe use the information collected for the following purposes:\n\nTo provide you with the services and functions of the Application.\nTo personalize your experience and offer you relevant content and recommendations.\nTo communicate with you and respond to your questions and requests.\nTo improve and optimize our Application and develop new products and services.\nFor analysis and statistics purposes.\nShare your Information\n\nWe will not share your personal information with third parties without your consent, except in the following circumstances:\n\nWhen necessary to provide you with requested services, such as making a travel reservation.\nWhen necessary to comply with the law, a court order or a legally valid request from authorities.\nWhen necessary to protect our rights, properties or the safety of our users or the general public.\nSecurity of your Information\n\nWe take reasonable measures to protect personal information from loss, theft, misuse, unauthorized access, disclosure, alteration and destruction.\n\nChanges to this Privacy Policy\n\nWe may update this Privacy Policy from time to time. We recommend that you periodically review this page to be aware of any changes. The date of the last update will be indicated at the end of this Privacy Policy.\n\nHow to Contact Us\n\nIf you have any questions about this Privacy Policy, you can contact us at [contact email].\n\nLast update: [date of the last update of the Privacy Policy].',
      'fr':
          'Cette politique de confidentialité décrit comment ToGo (« nous », « notre » ou « l\'application ») collecte, utilise et partage des informations personnelles lorsque vous utilisez notre application mobile ToGo (l\'« Application »). En utilisant l\'Application, vous acceptez le traitement de vos informations personnelles conformément à la présente Politique de confidentialité.\n\nInformations que nous collectons\n\nLorsque vous utilisez notre Application, nous pouvons collecter et traiter les informations suivantes :\n\nInformations que vous nous fournissez : Nous pouvons collecter des informations que vous nous fournissez volontairement lors de votre inscription à l\'Application, telles que votre nom, votre adresse e-mail, votre numéro de téléphone et vos préférences de voyage.\n\nInformations d\'utilisation : nous pouvons collecter des informations sur la manière dont vous utilisez l\'Application, telles que les pages que vous visitez, les fonctionnalités que vous utilisez et la fréquence à laquelle vous accédez à l\'Application.\n\nInformations sur l\'appareil : nous pouvons collecter des informations sur votre appareil mobile, notamment le modèle de l\'appareil, le système d\'exploitation, les identifiants uniques de l\'appareil et les données du réseau mobile.\n\nComment nous utilisons vos informations\n\nNous utilisons les informations collectées aux fins suivantes :\n\nPour vous fournir les services et fonctions de l’Application.\nPour personnaliser votre expérience et vous proposer du contenu et des recommandations pertinentes.\nPour communiquer avec vous et répondre à vos questions et demandes.\nAméliorer et optimiser notre Application et développer de nouveaux produits et services.\nÀ des fins d’analyse et de statistiques.\nPartagez vos informations\n\nNous ne partagerons pas vos informations personnelles avec des tiers sans votre consentement, sauf dans les circonstances suivantes :\n\nLorsque cela est nécessaire pour vous fournir les services demandés, comme effectuer une réservation de voyage.\nLorsque cela est nécessaire pour se conformer à la loi, à une ordonnance du tribunal ou à une demande légalement valable des autorités.\nLorsque cela est nécessaire pour protéger nos droits, nos propriétés ou la sécurité de nos utilisateurs ou du grand public.\nSécurité de vos informations\n\nNous prenons des mesures raisonnables pour protéger les informations personnelles contre la perte, le vol, l\'utilisation abusive, l\'accès non autorisé, la divulgation, l\'altération et la destruction.\n\nModifications de cette politique de confidentialité\n\nNous pouvons mettre à jour cette politique de confidentialité de temps à autre. Nous vous recommandons de consulter périodiquement cette page pour être au courant de tout changement. La date de la dernière mise à jour sera indiquée à la fin de la présente Politique de Confidentialité.\n\nComment nous contacter\n\nSi vous avez des questions concernant cette politique de confidentialité, vous pouvez nous contacter à [e-mail de contact].\n\nDernière mise à jour : [date de la dernière mise à jour de la Politique de Confidentialité].',
      'it':
          'La presente Informativa sulla privacy descrive come ToGo (\"noi\", \"nostro\" o \"l\'app\") raccoglie, utilizza e condivide le informazioni personali quando utilizzi la nostra applicazione mobile ToGo (l\'\"Applicazione\"). Utilizzando l\'Applicazione, accetti il ​​trattamento dei tuoi dati personali in conformità con la presente Informativa sulla privacy.\n\nInformazioni che raccogliamo\n\nQuando utilizzi la nostra Applicazione, potremmo raccogliere ed elaborare le seguenti informazioni:\n\nInformazioni che ci fornisci: potremmo raccogliere informazioni che ci fornisci volontariamente al momento della registrazione all\'Applicazione, come nome, indirizzo email, numero di telefono e preferenze di viaggio.\n\nInformazioni sull\'utilizzo: potremmo raccogliere informazioni su come utilizzi l\'Applicazione, come le pagine che visiti, le funzionalità che utilizzi e la frequenza con cui accedi all\'Applicazione.\n\nInformazioni sul dispositivo: potremmo raccogliere informazioni sul tuo dispositivo mobile, inclusi modello del dispositivo, sistema operativo, identificatori univoci del dispositivo e dati della rete mobile.\n\nCome utilizziamo le tue informazioni\n\nUtilizziamo le informazioni raccolte per i seguenti scopi:\n\nPer fornirti i servizi e le funzioni dell\'Applicazione.\nPer personalizzare la tua esperienza e offrirti contenuti e consigli pertinenti.\nPer comunicare con te e rispondere alle tue domande e richieste.\nPer migliorare e ottimizzare la nostra Applicazione e sviluppare nuovi prodotti e servizi.\nPer scopi di analisi e statistica.\nCondividi le tue informazioni\n\nNon condivideremo le tue informazioni personali con terzi senza il tuo consenso, tranne nelle seguenti circostanze:\n\nQuando necessario per fornirti i servizi richiesti, come effettuare una prenotazione di viaggio.\nQuando necessario per rispettare la legge, un ordine del tribunale o una richiesta legalmente valida delle autorità.\nQuando necessario per proteggere i nostri diritti, le nostre proprietà o la sicurezza dei nostri utenti o del pubblico in generale.\nSicurezza delle tue informazioni\n\nAdottiamo misure ragionevoli per proteggere le informazioni personali da perdita, furto, uso improprio, accesso non autorizzato, divulgazione, alterazione e distruzione.\n\nModifiche alla presente Informativa sulla privacy\n\nPotremmo aggiornare la presente Informativa sulla privacy di tanto in tanto. Ti consigliamo di rivedere periodicamente questa pagina per essere a conoscenza di eventuali modifiche. La data dell\'ultimo aggiornamento sarà indicata in fondo alla presente Privacy Policy.\n\nCome contattarci\n\nIn caso di domande sulla presente Informativa sulla privacy, è possibile contattarci all\'indirizzo [e-mail di contatto].\n\nUltimo aggiornamento: [data dell\'ultimo aggiornamento della Privacy Policy].',
      'ja':
          'このプライバシー ポリシーでは、ToGo モバイル アプリケーション (「アプリケーション」) を使用する際に、ToGo (「当社」、「当社の」、または「アプリ」) が個人情報をどのように収集、使用、および共有するかについて説明します。アプリケーションを使用すると、このプライバシー ポリシーに従って個人情報が処理されることに同意したものとみなされます。\n\n当社が収集する情報\n\nお客様が当社のアプリケーションを使用する場合、当社は次の情報を収集して処理する場合があります。\n\nお客様が当社に提供する情報：当社は、お客様の名前、電子メールアドレス、電話番号、旅行の希望など、アプリケーションに登録する際にお客様が自発的に当社に提供した情報を収集する場合があります。\n\n使用状況情報: 当社は、アクセスしたページ、使用した機能、アプリケーションへのアクセス頻度など、アプリケーションの使用方法に関する情報を収集する場合があります。\n\nデバイス情報: 当社は、デバイスのモデル、オペレーティング システム、固有のデバイス識別子、モバイル ネットワーク データなど、お客様のモバイル デバイスに関する情報を収集する場合があります。\n\nお客様の情報の使用方法\n\n当社は収集した情報を次の目的で使用します。\n\nアプリケーションのサービスと機能を提供するため。\nお客様のエクスペリエンスをパーソナライズし、関連するコンテンツや推奨事項を提供するため。\nお客様と連絡を取り、お客様の質問やリクエストに対応するため。\n当社のアプリケーションを改善および最適化し、新しい製品やサービスを開発するため。\n分析と統計の目的。\n情報を共有する\n\n当社は、以下の場合を除き、お客様の個人情報をお客様の同意なしに第三者と共有することはありません。\n\n旅行の予約など、リクエストされたサービスを提供するために必要な場合。\n法律、裁判所命令、または当局からの法的に有効な要求を遵守するために必要な場合。\n当社の権利、財産、ユーザーまたは一般大衆の安全を保護するために必要な場合。\nあなたの情報のセキュリティ\n\n当社は、個人情報を紛失、盗難、悪用、不正アクセス、開示、改ざんおよび破壊から保護するために合理的な措置を講じます。\n\nこのプライバシーポリシーの変更\n\n当社は、このプライバシー ポリシーを随時更新することがあります。このページを定期的に確認して、変更を認識することをお勧めします。最終更新日は、このプライバシー ポリシーの最後に記載されています。\n\nお問い合わせ方法\n\nこのプライバシー ポリシーについてご質問がある場合は、[連絡先メールアドレス] までご連絡ください。\n\n最終更新日: [プライバシー ポリシーの最終更新日]。',
      'pt':
          'Esta Política de Privacidade descreve como o ToGo (\"nós\", \"nosso\" ou \"o aplicativo\") coleta, usa e compartilha informações pessoais quando você usa nosso aplicativo móvel ToGo (o \"Aplicativo\"). Ao utilizar o Aplicativo, você concorda com o processamento de suas informações pessoais de acordo com esta Política de Privacidade.\n\nInformações que coletamos\n\nQuando você usa nosso Aplicativo, podemos coletar e processar as seguintes informações:\n\nInformações que você nos fornece: podemos coletar informações que você nos fornece voluntariamente ao se registrar no Aplicativo, como seu nome, endereço de e-mail, número de telefone e preferências de viagem.\n\nInformações de uso: Podemos coletar informações sobre como você usa o Aplicativo, como as páginas que você visita, os recursos que você usa e com que frequência você acessa o Aplicativo.\n\nInformações do dispositivo: podemos coletar informações sobre o seu dispositivo móvel, incluindo modelo do dispositivo, sistema operacional, identificadores exclusivos do dispositivo e dados da rede móvel.\n\nComo usamos suas informações\n\nUtilizamos as informações coletadas para os seguintes fins:\n\nPara fornecer a você os serviços e funções do Aplicativo.\nPara personalizar sua experiência e oferecer conteúdos e recomendações relevantes.\nPara comunicar consigo e responder às suas perguntas e pedidos.\nPara melhorar e otimizar nosso Aplicativo e desenvolver novos produtos e serviços.\nPara fins de análise e estatística.\nCompartilhe suas informações\n\nNão compartilharemos suas informações pessoais com terceiros sem o seu consentimento, exceto nas seguintes circunstâncias:\n\nQuando necessário para lhe fornecer os serviços solicitados, como fazer uma reserva de viagem.\nQuando necessário para cumprir a lei, uma ordem judicial ou uma solicitação legalmente válida das autoridades.\nQuando necessário para proteger os nossos direitos, propriedades ou a segurança dos nossos utilizadores ou do público em geral.\nSegurança das suas informações\n\nTomamos medidas razoáveis ​​para proteger as informações pessoais contra perda, roubo, uso indevido, acesso não autorizado, divulgação, alteração e destruição.\n\nAlterações nesta Política de Privacidade\n\nPoderemos atualizar esta Política de Privacidade de tempos em tempos. Recomendamos que você revise periodicamente esta página para estar ciente de quaisquer alterações. A data da última atualização será indicada no final desta Política de Privacidade.\n\nComo entrar em contato conosco\n\nSe você tiver alguma dúvida sobre esta Política de Privacidade, entre em contato conosco pelo e-mail [e-mail de contato].\n\nÚltima atualização: [data da última atualização da Política de Privacidade].',
      'zh_Hans':
          '本隐私政策描述了当您使用我们的 ToGo 移动应用程序（“应用程序”）时，ToGo（“我们”、“我们的”或“应用程序”）如何收集、使用和共享个人信息。使用该应用程序，即表示您同意根据本隐私政策处理您的个人信息。\n\n我们收集的信息\n\n当您使用我们的应用程序时，我们可能会收集和处理以下信息：\n\n您向我们提供的信息：我们可能会收集您在注册应用程序时自愿向我们提供的信息，例如您的姓名、电子邮件地址、电话号码和旅行偏好。\n\n使用信息：我们可能会收集有关您如何使用应用程序的信息，例如您访问的页面、您使用的功能以及您访问应用程序的频率。\n\n设备信息：我们可能会收集有关您的移动设备的信息，包括设备型号、操作系统、唯一设备标识符和移动网络数据。\n\n我们如何使用您的信息\n\n我们将收集的信息用于以下目的：\n\n为您提供应用程序的服务和功能。\n个性化您的体验并为您提供相关内容和建议。\n与您沟通并回答您的问题和请求。\n改进和优化我们的应用程序并开发新产品和服务。\n用于分析和统计目的。\n分享您的信息\n\n未经您的同意，我们不会与第三方共享您的个人信息，但以下情况除外：\n\n必要时向您提供所要求的服务，例如旅行预订。\n当有必要遵守法律、法院命令或当局的合法有效要求时。\n当有必要保护我们的权利、财产或我们的用户或公众的安全时。\n您的信息安全\n\n我们采取合理措施保护个人信息免遭丢失、盗窃、滥用、未经授权的访问、披露、更改和破坏。\n\n本隐私政策的变更\n\n我们可能会不时更新本隐私政策。我们建议您定期查看此页面以了解任何更改。最后更新日期将在本隐私政策末尾注明。\n\n如何联系我们\n\n如果您对本隐私政策有任何疑问，您可以通过[联系电子邮件]与我们联系。\n\n最后更新：[隐私政策最后更新的日期]。',
    },
    'khj6zqo7': {
      'es': 'Términos y Condiciones',
      'ar': 'سياسة الخصوصية',
      'ca': 'Política de Privadesa',
      'de': 'Datenschutzrichtlinie',
      'en': 'Privacy Policy',
      'fr': 'Politique de confidentialité',
      'it': 'politica sulla riservatezza',
      'ja': 'プライバシーポリシー',
      'pt': 'Política de privacidade',
      'zh_Hans': '隐私政策',
    },
    '44hf7sos': {
      'es': 'Home',
      'ar': 'بيت',
      'ca': 'Home',
      'de': 'heim',
      'en': 'home',
      'fr': 'maison',
      'it': 'casa',
      'ja': '家',
      'pt': 'lar',
      'zh_Hans': '家',
    },
  },
  // ProfilePage
  {
    '53p2vxwj': {
      'es': 'Correo electrónico',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'bezzw2sq': {
      'es': 'Cambiar contraseña',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'oweuq8y3': {
      'es': '__',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
  },
  // EditProfilePage
  {
    'htbw6ds1': {
      'es': 'Cambiar la dirección de\ncorreo electrónico',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'py8yxr5m': {
      'es': 'Correo electrónico',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'rl4d229u': {
      'es': 'Guardar cambios',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'nss948qr': {
      'es': 'Home',
      'ar': 'بيت',
      'ca': 'Home',
      'de': 'heim',
      'en': 'home',
      'fr': 'maison',
      'it': 'casa',
      'ja': '家',
      'pt': 'lar',
      'zh_Hans': '家',
    },
  },
  // ActivityDetails
  {
    'zwvaghl9': {
      'es': 'Descripción',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'hfngaxjn': {
      'es': 'Home',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
  },
  // HomePageResults
  {
    'jz5ghfdn': {
      'es': 'Buscar...',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'psarmhw3': {
      'es': 'Buscar',
      'ar': 'بحث',
      'ca': 'Cerca',
      'de': 'Suche',
      'en': 'Look for',
      'fr': 'Chercher',
      'it': 'Cercare',
      'ja': '探す',
      'pt': 'Procurar',
      'zh_Hans': '寻找',
    },
  },
  // Miscellaneous
  {
    'p05s6yxh': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'u6jyugm8': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'igpdupee': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'kq42z25m': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    '3tdr3st5': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    '2g0ka0p7': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'inntiy2f': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'l2tjp6on': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'g3juqkl7': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'ah0e04n4': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'nki6ypxg': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'ybuicklq': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    '4qhwu4eq': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'janwp6jc': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    '4wuoy8pd': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'bmt04cun': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'snjyzn0v': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'sbcr6ahm': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'ke469tz3': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    '1u1xnz9i': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'fs10fci2': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'ymj231lo': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'x0q59a13': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'pcj2mch0': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'kkv5clye': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
    'i8mb2ebj': {
      'es': '',
      'ar': '',
      'ca': '',
      'de': '',
      'en': '',
      'fr': '',
      'it': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
